apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: mysql-namespace

spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
